### ISSUE TITLE
Confidence scores

### ISSUE THREAD

**Issue by munish0838** [bleugreen/deeprhythm#1]
Hi, is there a way we can also get the confidence scores for the predictions of the bpm values?

**Comment by bleugreen** [comment]
Sure! Just added a flag to return the maximum probability of the prediction, to use it:

```
pred = DeepRhythmPredictor()
bpm, confidence = pred.predict(audio_path, include_confidence=True)
```

This is a pretty simple implementation, and I haven't tested it much. Let me know if it works for you!
