### ISSUE TITLE
Dynamic tempo? 

### ISSUE THREAD

**Issue by drscotthawley** [bleugreen/deeprhythm#4]
Hi! Thanks for sharing your code. I found it after having some trouble with librosa's dynamic tempo estimation outputting some wild values, and/or not offering sufficient tempo resolution (only +/- 5 bpm  for my example) 

I tried your code and it works -- the estimation is a bit high IMHO for my song as when I tap it on a metronome I get 110 bpm and DeepRythm outputs 112 bpm --- but in any case, how do we get running estimates of tempo over time from DeepRhythm? 

Thanks!

**Comment by bleugreen** [comment]
Hi! Apologies for the delay I'm just seeing this. The model estimates tempo on 8-second increments, and the resulting 'windows' are then softmaxed to get the global output. I can easily add a flag/option to get the output per-window though. 

Would it be more convenient as a list of raw tempos or dicts with {start_time, tempo}?

**Comment by pauloau15** [comment]
@bleugreen That would be very usefull indeed! Specially for songs where we have BPM changes, so if we have a flag that output per segment, we could see those BPM changes

**Comment by bleugreen** [comment]
added `DeepRhythmPredictor.predict_per_frame(path)` which returns a list of tempos per 8s chunk of audio. Let me know if dicts / times would be more helpful
