### ISSUE TITLE
Sample Rate influences model?

### ISSUE THREAD

**Issue by jvaleroliet** [bleugreen/deeprhythm#7]
Hi, I see that in your code audio is resampled to _22050_. Is this a must? If I use other sampling rate would it affect the model?
Thanks in advance

**Comment by bleugreen** [comment]
To be honest, I'm not sure how the model would be affected by other sampling rates (worth experimenting with), but I can explain the rationale behind 22050:
- reduces amount of data in typical 'CD quality' audio (44.1kHz) by half
- allows spectrogram capture of frequencies up to 11kHz, which is more than enough detail for tempo frequencies

i.e. it 'lightens' the audio without losing the details, provides a consistent baseline for feature extraction, and is just low enough that I'm almost always downsampling, thus not introducing any sampling artifacts
